server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
data:
  database:
    driver: mysql
    source: "${MYSQL_SOURCE}"
  redis:
    addr: "${REDIS_ADDR}"
    read_timeout: 0.2s
    write_timeout: 0.2s
  object_storage:
    bucket: "test"
    secret_id: "some_access_key1"
    secret_key: "some_secret_key1"
    endpoint: "http://jnoj-s3:8333"
service:
  message_queue:
    address: "amqp://admin:admin@rabbitmq:5672/"

consul:
  address: consul:8500
  scheme: http