server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
data:
  database:
    driver: mysql
    source: "${MYSQL_SOURCE}"
  redis:
    addr: "${REDIS_ADDR}"
    read_timeout: 0.2s
    write_timeout: 0.2s
  mongodb:
    uri: "mongodb://root:123456@mongo:27017/"
    database: "jnoj"

consul:
  address: consul:8500
  scheme: http