version: '3'

services:
  phpmyadmin:
    container_name: jnoj-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 9500:80
    depends_on:
      - mysql
    environment: 
      PMA_USER: root
      PMA_PASSWORD: 123456
    links:
      - mysql:db

networks:
  jnoj_net:
