version: '3'

services:
  # 前端项目
  web:
    container_name: jnoj-web
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "8091:3000"
    environment:
      NODE_ENV=production
      API_BASE_URL=${JNOJ_HOST}/api
      API_WS_URL=${JNOJ_HOST}/admin-api
      ADMIN_API_BASE_URL=${JNOJ_WS_HOST}/api/ws

  # 后端 api 接口
  interface-api:
    container_name: jnoj-interface-api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd app/interface && make build && ./bin/server -conf ./configs/config.yaml"
    environment:
      MYSQL_SOURCE: ${MYSQL_SOURCE}
      REDIS_ADDR: ${REDIS_ADDR}
      JNOJ_HOST: ${JNOJ_HOST}
      JWT_SECRET: ${JWT_SECRET}
      S3_SECRET_ID: ${S3_SECRET_ID}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - 8092:8000
    volumes:
      - ..:/go/src/jnoj
    depends_on:
      - mysql
      - consul
      - redis
    restart: always

  # 管理后台 api 接口
  admin-api:
    container_name: jnoj-admin-api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd app/admin && make build && ./bin/server -conf ./configs/config.yaml"
    environment:
      MYSQL_SOURCE: ${MYSQL_SOURCE}
      REDIS_ADDR: ${REDIS_ADDR}
      JNOJ_HOST: ${JNOJ_HOST}
      JWT_SECRET: ${JWT_SECRET}
      S3_SECRET_ID: ${S3_SECRET_ID}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - 8093:8000
    volumes:
      - ..:/go/src/jnoj
    depends_on:
      - mysql
      - consul
      - redis
    restart: always

  # 测评沙箱
  sandbox:
    container_name: jnoj-sandbox-api
    build:
      context: .
      dockerfile: DockerfileSandbox
    command: bash -c "cd app/sandbox && make build && ./bin/server -conf ./configs/config.yaml"
    environment:
      MYSQL_SOURCE: ${MYSQL_SOURCE}
      REDIS_ADDR: ${REDIS_ADDR}
      JNOJ_HOST: ${JNOJ_HOST}
      S3_SECRET_ID: ${S3_SECRET_ID}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    volumes:
      - ..:/go/src/sandbox
    depends_on:
      - mysql
      - redis
      - consul
    restart: always
    privileged: true

  # nginx 反向代理，用于将以上定义的 web、interface-api、admin-api 和 seaweedfs 文件储存，聚合在一个端口中
  nginx:
    container_name: jnoj-nginx
    image: nginx:latest
    ports:
      - "8011:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - interface-api
      - admin-api

networks:
  jnoj_net:
