version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd app/interface && make build && ./bin/server -conf ./configs/config.yaml"
    environment:
      MYSQL_SOURCE: root:123456@tcp(mysql:3306)/jnoj?charset=utf8mb4&parseTime=True&loc=Local
      REDIS_ADDR: redis:6379
      MONGODB_URI: mongodb://root:123456@mongo:27017
    ports:
      - 8092:8000
    volumes:
      - ..:/go/src/jnoj
    depends_on:
      - mysql
      - consul
      - redis
    restart: always

  sandbox:
    build:
      context: .
      dockerfile: DockerfileSandbox
    command: bash -c "cd app/sandbox && make build && ./bin/server -conf ./configs/config.yaml"
    environment:
      MYSQL_SOURCE: root:123456@tcp(mysql:3306)/jnoj?charset=utf8mb4&parseTime=True&loc=Local
      REDIS_ADDR: redis:6379
      MONGODB_URI: mongodb://root:123456@mongo:27017
    volumes:
      - ..:/go/src/sandbox
    depends_on:
      - mysql
      - redis
      - consul
    restart: always
    privileged: true

  consul:
    image: consul:latest
    ports:
      - "9502:8500"
    command: agent -server -bootstrap -ui -node=1 -client=0.0.0.0

  mongo:
    image: mongo:5.0.5
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ../data/mongo/db:/data/db

  redis:
    image: redis:5.0-alpine
    command: redis-server
    volumes:
      - ../data/redis:/data
    restart: always

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ../data/mysql/logs:/logs
      - ../data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: jnoj
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai

networks:
  jnoj_net:
