version: '3'

services:
  redis:
    container_name: jnoj-redis
    image: redis:5.0-alpine
    command: redis-server
    volumes:
      - ../data/redis:/data
    restart: always

  mysql:
    container_name: jnoj-mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ../data/mysql/logs:/logs
      - ../data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: jnoj
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai

networks:
  jnoj_net:
