version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9500:80
    depends_on:
      - mysql
    environment: 
      PMA_USER: root
      PMA_PASSWORD: 123456
    links:
      - mysql:db

  mongo-express:
    image: mongo-express
    ports:
      - "9501:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    restart: always
    depends_on:
      - mongo
