server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 60s
data:
  database:
    driver: mysql
    source: "${MYSQL_SOURCE}"
  redis:
    addr: "${REDIS_ADDR}"
    read_timeout: 0.2s
    write_timeout: 0.2s
  object_storage:
    private_bucket:
      bucket: "private"
      secret_id: "jnoj_access_key1"
      secret_key: "jnoj_secret_key1"
      endpoint: "http://jnoj-s3:8333"
    public_bucket:
      bucket: "public"
      secret_id: "jnoj_access_key1"
      secret_key: "jnoj_secret_key1"
      endpoint: "http://jnoj-s3:8333"
service:
  message_queue:
    address: "amqp://admin:admin@rabbitmq:5672/"
consul:
  address: consul:8500
  scheme: http
sandbox:
  testlib_path: "/go/src/sandbox/third_party/testlib"