server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 60s
data:
  database:
    driver: mysql
    source: "${MYSQL_SOURCE}"
  redis:
    addr: "${REDIS_ADDR}"
    read_timeout: 0.2s
    write_timeout: 0.2s
  object_storage:
    private_bucket:
      bucket: "${S3_PRIVATE_BUCKET_NAME}"
      secret_id: "${S3_PRIVATE_SECRET_ID}"
      secret_key: "${S3_PRIVATE_SECRET_KEY}"
      endpoint: "${S3_PRIVATE_ENDPOINT}"
    public_bucket:
      bucket: "${S3_PUBLIC_BUCKET_NAME}"
      secret_id: "${S3_PUBLIC_SECRET_ID}"
      secret_key: "${S3_PUBLIC_SECRET_KEY}"
      endpoint: "${S3_PUBLIC_ENDPOINT}"
  message_queue:
    address: "amqp://admin:admin@rabbitmq:5672/"
consul:
  address: consul:8500
  scheme: http
sandbox:
  testlib_path: "/go/src/sandbox/third_party/testlib"