// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: v1/contest_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContestErrorReason int32

const (
	ContestErrorReason_CONTEST_NOT_FOUND          ContestErrorReason = 0
	ContestErrorReason_CONTEST_PROBLEM_NOT_FOUND  ContestErrorReason = 1
	ContestErrorReason_CONTEST_ALREADY_REGISTERED ContestErrorReason = 2
)

// Enum value maps for ContestErrorReason.
var (
	ContestErrorReason_name = map[int32]string{
		0: "CONTEST_NOT_FOUND",
		1: "CONTEST_PROBLEM_NOT_FOUND",
		2: "CONTEST_ALREADY_REGISTERED",
	}
	ContestErrorReason_value = map[string]int32{
		"CONTEST_NOT_FOUND":          0,
		"CONTEST_PROBLEM_NOT_FOUND":  1,
		"CONTEST_ALREADY_REGISTERED": 2,
	}
)

func (x ContestErrorReason) Enum() *ContestErrorReason {
	p := new(ContestErrorReason)
	*p = x
	return p
}

func (x ContestErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContestErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_contest_error_proto_enumTypes[0].Descriptor()
}

func (ContestErrorReason) Type() protoreflect.EnumType {
	return &file_v1_contest_error_proto_enumTypes[0]
}

func (x ContestErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContestErrorReason.Descriptor instead.
func (ContestErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_v1_contest_error_proto_rawDescGZIP(), []int{0}
}

var File_v1_contest_error_proto protoreflect.FileDescriptor

var file_v1_contest_error_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6a, 0x6e, 0x6f, 0x6a, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2a, 0x82, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x11, 0x43, 0x4f, 0x4e, 0x54, 0x45,
	0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x1a, 0x04,
	0xa8, 0x45, 0x94, 0x03, 0x12, 0x23, 0x0a, 0x19, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x53, 0x54, 0x5f,
	0x50, 0x52, 0x4f, 0x42, 0x4c, 0x45, 0x4d, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03, 0x12, 0x24, 0x0a, 0x1a, 0x43, 0x4f, 0x4e,
	0x54, 0x45, 0x53, 0x54, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x52, 0x45, 0x47,
	0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x02, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x1a,
	0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x15, 0x5a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_contest_error_proto_rawDescOnce sync.Once
	file_v1_contest_error_proto_rawDescData = file_v1_contest_error_proto_rawDesc
)

func file_v1_contest_error_proto_rawDescGZIP() []byte {
	file_v1_contest_error_proto_rawDescOnce.Do(func() {
		file_v1_contest_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_contest_error_proto_rawDescData)
	})
	return file_v1_contest_error_proto_rawDescData
}

var file_v1_contest_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_contest_error_proto_goTypes = []interface{}{
	(ContestErrorReason)(0), // 0: jnoj.interface.v1.ContestErrorReason
}
var file_v1_contest_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_contest_error_proto_init() }
func file_v1_contest_error_proto_init() {
	if File_v1_contest_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_contest_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_contest_error_proto_goTypes,
		DependencyIndexes: file_v1_contest_error_proto_depIdxs,
		EnumInfos:         file_v1_contest_error_proto_enumTypes,
	}.Build()
	File_v1_contest_error_proto = out.File
	file_v1_contest_error_proto_rawDesc = nil
	file_v1_contest_error_proto_goTypes = nil
	file_v1_contest_error_proto_depIdxs = nil
}
