// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.2
// - protoc             v3.19.4
// source: v1/contest.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationContestServiceGetContest = "/jnoj.interface.v1.ContestService/GetContest"
const OperationContestServiceGetContestProblem = "/jnoj.interface.v1.ContestService/GetContestProblem"
const OperationContestServiceListContestProblems = "/jnoj.interface.v1.ContestService/ListContestProblems"
const OperationContestServiceListContestUsers = "/jnoj.interface.v1.ContestService/ListContestUsers"
const OperationContestServiceListContests = "/jnoj.interface.v1.ContestService/ListContests"

type ContestServiceHTTPServer interface {
	GetContest(context.Context, *GetContestRequest) (*Contest, error)
	GetContestProblem(context.Context, *GetContestProblemRequest) (*ContestProblem, error)
	ListContestProblems(context.Context, *ListContestProblemsRequest) (*ListContestProblemsResponse, error)
	ListContestUsers(context.Context, *ListContestUsersRequest) (*ListContestUsersResponse, error)
	ListContests(context.Context, *ListContestsRequest) (*ListContestsResponse, error)
}

func RegisterContestServiceHTTPServer(s *http.Server, srv ContestServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/contests", _ContestService_ListContests0_HTTP_Handler(srv))
	r.GET("/contests/{id}", _ContestService_GetContest0_HTTP_Handler(srv))
	r.GET("/contests/{id}/problems", _ContestService_ListContestProblems0_HTTP_Handler(srv))
	r.GET("/contests/{id}/problems/{key}", _ContestService_GetContestProblem0_HTTP_Handler(srv))
	r.GET("/contests/{id}/users", _ContestService_ListContestUsers0_HTTP_Handler(srv))
}

func _ContestService_ListContests0_HTTP_Handler(srv ContestServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListContestsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContestServiceListContests)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListContests(ctx, req.(*ListContestsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListContestsResponse)
		return ctx.Result(200, reply)
	}
}

func _ContestService_GetContest0_HTTP_Handler(srv ContestServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetContestRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContestServiceGetContest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContest(ctx, req.(*GetContestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Contest)
		return ctx.Result(200, reply)
	}
}

func _ContestService_ListContestProblems0_HTTP_Handler(srv ContestServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListContestProblemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContestServiceListContestProblems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListContestProblems(ctx, req.(*ListContestProblemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListContestProblemsResponse)
		return ctx.Result(200, reply)
	}
}

func _ContestService_GetContestProblem0_HTTP_Handler(srv ContestServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetContestProblemRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContestServiceGetContestProblem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContestProblem(ctx, req.(*GetContestProblemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ContestProblem)
		return ctx.Result(200, reply)
	}
}

func _ContestService_ListContestUsers0_HTTP_Handler(srv ContestServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListContestUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContestServiceListContestUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListContestUsers(ctx, req.(*ListContestUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListContestUsersResponse)
		return ctx.Result(200, reply)
	}
}

type ContestServiceHTTPClient interface {
	GetContest(ctx context.Context, req *GetContestRequest, opts ...http.CallOption) (rsp *Contest, err error)
	GetContestProblem(ctx context.Context, req *GetContestProblemRequest, opts ...http.CallOption) (rsp *ContestProblem, err error)
	ListContestProblems(ctx context.Context, req *ListContestProblemsRequest, opts ...http.CallOption) (rsp *ListContestProblemsResponse, err error)
	ListContestUsers(ctx context.Context, req *ListContestUsersRequest, opts ...http.CallOption) (rsp *ListContestUsersResponse, err error)
	ListContests(ctx context.Context, req *ListContestsRequest, opts ...http.CallOption) (rsp *ListContestsResponse, err error)
}

type ContestServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewContestServiceHTTPClient(client *http.Client) ContestServiceHTTPClient {
	return &ContestServiceHTTPClientImpl{client}
}

func (c *ContestServiceHTTPClientImpl) GetContest(ctx context.Context, in *GetContestRequest, opts ...http.CallOption) (*Contest, error) {
	var out Contest
	pattern := "/contests/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContestServiceGetContest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ContestServiceHTTPClientImpl) GetContestProblem(ctx context.Context, in *GetContestProblemRequest, opts ...http.CallOption) (*ContestProblem, error) {
	var out ContestProblem
	pattern := "/contests/{id}/problems/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContestServiceGetContestProblem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ContestServiceHTTPClientImpl) ListContestProblems(ctx context.Context, in *ListContestProblemsRequest, opts ...http.CallOption) (*ListContestProblemsResponse, error) {
	var out ListContestProblemsResponse
	pattern := "/contests/{id}/problems"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContestServiceListContestProblems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ContestServiceHTTPClientImpl) ListContestUsers(ctx context.Context, in *ListContestUsersRequest, opts ...http.CallOption) (*ListContestUsersResponse, error) {
	var out ListContestUsersResponse
	pattern := "/contests/{id}/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContestServiceListContestUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ContestServiceHTTPClientImpl) ListContests(ctx context.Context, in *ListContestsRequest, opts ...http.CallOption) (*ListContestsResponse, error) {
	var out ListContestsResponse
	pattern := "/contests"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContestServiceListContests))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
