// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsContestNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ContestErrorReason_CONTEST_NOT_FOUND.String() && e.Code == 404
}

func ErrorContestNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ContestErrorReason_CONTEST_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsContestProblemNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ContestErrorReason_CONTEST_PROBLEM_NOT_FOUND.String() && e.Code == 404
}

func ErrorContestProblemNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ContestErrorReason_CONTEST_PROBLEM_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsContestAlreadyRegistered(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ContestErrorReason_CONTEST_ALREADY_REGISTERED.String() && e.Code == 400
}

func ErrorContestAlreadyRegistered(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ContestErrorReason_CONTEST_ALREADY_REGISTERED.String(), fmt.Sprintf(format, args...))
}
