// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.4
// - protoc             v3.19.4
// source: v1/problem.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	auth "jnoj/internal/middleware/auth"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

// auth.
const OperationProblemServiceCreateProblem = "/jnoj.interface.v1.ProblemService/CreateProblem"
const OperationProblemServiceCreateProblemFile = "/jnoj.interface.v1.ProblemService/CreateProblemFile"
const OperationProblemServiceCreateProblemStatement = "/jnoj.interface.v1.ProblemService/CreateProblemStatement"
const OperationProblemServiceCreateProblemTest = "/jnoj.interface.v1.ProblemService/CreateProblemTest"
const OperationProblemServiceDeleteProblemFile = "/jnoj.interface.v1.ProblemService/DeleteProblemFile"
const OperationProblemServiceDeleteProblemStatement = "/jnoj.interface.v1.ProblemService/DeleteProblemStatement"
const OperationProblemServiceDeleteProblemTest = "/jnoj.interface.v1.ProblemService/DeleteProblemTest"
const OperationProblemServiceGetProblem = "/jnoj.interface.v1.ProblemService/GetProblem"
const OperationProblemServiceGetProblemFile = "/jnoj.interface.v1.ProblemService/GetProblemFile"
const OperationProblemServiceGetProblemStatement = "/jnoj.interface.v1.ProblemService/GetProblemStatement"
const OperationProblemServiceGetProblemTest = "/jnoj.interface.v1.ProblemService/GetProblemTest"
const OperationProblemServiceGetProblemVerification = "/jnoj.interface.v1.ProblemService/GetProblemVerification"
const OperationProblemServiceListProblemFiles = "/jnoj.interface.v1.ProblemService/ListProblemFiles"
const OperationProblemServiceListProblemStatements = "/jnoj.interface.v1.ProblemService/ListProblemStatements"
const OperationProblemServiceListProblemStdCheckers = "/jnoj.interface.v1.ProblemService/ListProblemStdCheckers"
const OperationProblemServiceListProblemTests = "/jnoj.interface.v1.ProblemService/ListProblemTests"
const OperationProblemServiceListProblems = "/jnoj.interface.v1.ProblemService/ListProblems"
const OperationProblemServiceRunProblemFile = "/jnoj.interface.v1.ProblemService/RunProblemFile"
const OperationProblemServiceUpdateProblem = "/jnoj.interface.v1.ProblemService/UpdateProblem"
const OperationProblemServiceUpdateProblemChecker = "/jnoj.interface.v1.ProblemService/UpdateProblemChecker"
const OperationProblemServiceUpdateProblemFile = "/jnoj.interface.v1.ProblemService/UpdateProblemFile"
const OperationProblemServiceUpdateProblemStatement = "/jnoj.interface.v1.ProblemService/UpdateProblemStatement"
const OperationProblemServiceUpdateProblemTest = "/jnoj.interface.v1.ProblemService/UpdateProblemTest"
const OperationProblemServiceVerifyProblem = "/jnoj.interface.v1.ProblemService/VerifyProblem"

type ProblemServiceHTTPServer interface {
	CreateProblem(context.Context, *CreateProblemRequest) (*CreateProblemResponse, error)
	CreateProblemFile(context.Context, *CreateProblemFileRequest) (*ProblemFile, error)
	CreateProblemStatement(context.Context, *CreateProblemStatementRequest) (*ProblemStatement, error)
	CreateProblemTest(context.Context, *CreateProblemTestRequest) (*ProblemTest, error)
	DeleteProblemFile(context.Context, *DeleteProblemFileRequest) (*ProblemFile, error)
	DeleteProblemStatement(context.Context, *DeleteProblemStatementRequest) (*ProblemStatement, error)
	DeleteProblemTest(context.Context, *DeleteProblemTestRequest) (*emptypb.Empty, error)
	GetProblem(context.Context, *GetProblemRequest) (*Problem, error)
	GetProblemFile(context.Context, *GetProblemFileRequest) (*ProblemFile, error)
	GetProblemStatement(context.Context, *GetProblemStatementRequest) (*ProblemStatement, error)
	GetProblemTest(context.Context, *GetProblemTestRequest) (*ProblemTest, error)
	GetProblemVerification(context.Context, *GetProblemVerificationRequest) (*ProblemVerification, error)
	ListProblemFiles(context.Context, *ListProblemFilesRequest) (*ListProblemFilesResponse, error)
	ListProblemStatements(context.Context, *ListProblemStatementsRequest) (*ListProblemStatementsResponse, error)
	ListProblemStdCheckers(context.Context, *ListProblemStdCheckersRequest) (*ListProblemStdCheckersResponse, error)
	ListProblemTests(context.Context, *ListProblemTestsRequest) (*ListProblemTestsResponse, error)
	ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error)
	RunProblemFile(context.Context, *RunProblemFileRequest) (*emptypb.Empty, error)
	UpdateProblem(context.Context, *UpdateProblemRequest) (*Problem, error)
	UpdateProblemChecker(context.Context, *UpdateProblemCheckerRequest) (*emptypb.Empty, error)
	UpdateProblemFile(context.Context, *UpdateProblemFileRequest) (*ProblemFile, error)
	UpdateProblemStatement(context.Context, *UpdateProblemStatementRequest) (*ProblemStatement, error)
	UpdateProblemTest(context.Context, *UpdateProblemTestRequest) (*ProblemTest, error)
	VerifyProblem(context.Context, *VerifyProblemRequest) (*emptypb.Empty, error)
}

func RegisterProblemServiceHTTPServer(s *http.Server, srv ProblemServiceHTTPServer) {
	s.Use("/jnoj.interface.v1.ProblemService/CreateProblem*", auth.User())
	s.Use("/jnoj.interface.v1.ProblemService/UpdateProblem*", auth.User())
	s.Use("/jnoj.interface.v1.ProblemService/DeleteProblem*", auth.User())
	s.Use("/jnoj.interface.v1.ProblemService/ListProblemFiles", auth.User())
	s.Use("/jnoj.interface.v1.ProblemService/ListProblemStdCheckers", auth.User())
	s.Use("/jnoj.interface.v1.ProblemService/ListProblemTests", auth.User())
	r := s.Route("/")
	r.GET("/problems", _ProblemService_ListProblems0_HTTP_Handler(srv))
	r.GET("/problems/{id}", _ProblemService_GetProblem0_HTTP_Handler(srv))
	r.POST("/problems", _ProblemService_CreateProblem0_HTTP_Handler(srv))
	r.PUT("/problems/{id}", _ProblemService_UpdateProblem0_HTTP_Handler(srv))
	r.GET("/problems/{id}/statements", _ProblemService_ListProblemStatements0_HTTP_Handler(srv))
	r.GET("/problems/{id}/statements", _ProblemService_GetProblemStatement0_HTTP_Handler(srv))
	r.POST("/problems/{id}/statements", _ProblemService_CreateProblemStatement0_HTTP_Handler(srv))
	r.PUT("/problems/{id}/statements/{sid}", _ProblemService_UpdateProblemStatement0_HTTP_Handler(srv))
	r.DELETE("/problems/{id}/statements/{sid}", _ProblemService_DeleteProblemStatement0_HTTP_Handler(srv))
	r.GET("/problems/{id}/tests", _ProblemService_ListProblemTests0_HTTP_Handler(srv))
	r.GET("/problems/{id}/tests", _ProblemService_GetProblemTest0_HTTP_Handler(srv))
	r.POST("/problems/{id}/tests", _ProblemService_CreateProblemTest0_HTTP_Handler(srv))
	r.PUT("/problems/{id}/tests/{tid}", _ProblemService_UpdateProblemTest0_HTTP_Handler(srv))
	r.DELETE("/problems/{id}/tests/{tid}", _ProblemService_DeleteProblemTest0_HTTP_Handler(srv))
	r.GET("/problems/{id}/files", _ProblemService_ListProblemFiles0_HTTP_Handler(srv))
	r.GET("/problems/{id}/files/{sid}", _ProblemService_GetProblemFile0_HTTP_Handler(srv))
	r.POST("/problems/{id}/files", _ProblemService_CreateProblemFile0_HTTP_Handler(srv))
	r.PUT("/problems/{id}/files/{sid}", _ProblemService_UpdateProblemFile0_HTTP_Handler(srv))
	r.DELETE("/problems/{id}/files/{sid}", _ProblemService_DeleteProblemFile0_HTTP_Handler(srv))
	r.POST("/problem_files/{sid}/run", _ProblemService_RunProblemFile0_HTTP_Handler(srv))
	r.GET("/problems/{id}/std_checkers", _ProblemService_ListProblemStdCheckers0_HTTP_Handler(srv))
	r.PUT("/problems/{id}/checkers", _ProblemService_UpdateProblemChecker0_HTTP_Handler(srv))
	r.POST("/problems/{id}/verify", _ProblemService_VerifyProblem0_HTTP_Handler(srv))
	r.GET("/problems/{id}/verification", _ProblemService_GetProblemVerification0_HTTP_Handler(srv))
}

func _ProblemService_ListProblems0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProblemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceListProblems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProblems(ctx, req.(*ListProblemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProblemsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_GetProblem0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProblemRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceGetProblem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProblem(ctx, req.(*GetProblemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Problem)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_CreateProblem0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProblemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceCreateProblem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProblem(ctx, req.(*CreateProblemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProblemResponse)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_UpdateProblem0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProblemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceUpdateProblem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProblem(ctx, req.(*UpdateProblemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Problem)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_ListProblemStatements0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProblemStatementsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceListProblemStatements)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProblemStatements(ctx, req.(*ListProblemStatementsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProblemStatementsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_GetProblemStatement0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProblemStatementRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceGetProblemStatement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProblemStatement(ctx, req.(*GetProblemStatementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemStatement)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_CreateProblemStatement0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProblemStatementRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceCreateProblemStatement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProblemStatement(ctx, req.(*CreateProblemStatementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemStatement)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_UpdateProblemStatement0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProblemStatementRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceUpdateProblemStatement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProblemStatement(ctx, req.(*UpdateProblemStatementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemStatement)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_DeleteProblemStatement0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProblemStatementRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceDeleteProblemStatement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProblemStatement(ctx, req.(*DeleteProblemStatementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemStatement)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_ListProblemTests0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProblemTestsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceListProblemTests)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProblemTests(ctx, req.(*ListProblemTestsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProblemTestsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_GetProblemTest0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProblemTestRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceGetProblemTest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProblemTest(ctx, req.(*GetProblemTestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemTest)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_CreateProblemTest0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProblemTestRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceCreateProblemTest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProblemTest(ctx, req.(*CreateProblemTestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemTest)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_UpdateProblemTest0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProblemTestRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceUpdateProblemTest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProblemTest(ctx, req.(*UpdateProblemTestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemTest)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_DeleteProblemTest0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProblemTestRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceDeleteProblemTest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProblemTest(ctx, req.(*DeleteProblemTestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_ListProblemFiles0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProblemFilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceListProblemFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProblemFiles(ctx, req.(*ListProblemFilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProblemFilesResponse)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_GetProblemFile0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProblemFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceGetProblemFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProblemFile(ctx, req.(*GetProblemFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemFile)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_CreateProblemFile0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProblemFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceCreateProblemFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProblemFile(ctx, req.(*CreateProblemFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemFile)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_UpdateProblemFile0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProblemFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceUpdateProblemFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProblemFile(ctx, req.(*UpdateProblemFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemFile)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_DeleteProblemFile0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProblemFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceDeleteProblemFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProblemFile(ctx, req.(*DeleteProblemFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemFile)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_RunProblemFile0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RunProblemFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceRunProblemFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RunProblemFile(ctx, req.(*RunProblemFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_ListProblemStdCheckers0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProblemStdCheckersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceListProblemStdCheckers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProblemStdCheckers(ctx, req.(*ListProblemStdCheckersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProblemStdCheckersResponse)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_UpdateProblemChecker0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProblemCheckerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceUpdateProblemChecker)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProblemChecker(ctx, req.(*UpdateProblemCheckerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_VerifyProblem0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerifyProblemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceVerifyProblem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.VerifyProblem(ctx, req.(*VerifyProblemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ProblemService_GetProblemVerification0_HTTP_Handler(srv ProblemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProblemVerificationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemServiceGetProblemVerification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProblemVerification(ctx, req.(*GetProblemVerificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProblemVerification)
		return ctx.Result(200, reply)
	}
}

type ProblemServiceHTTPClient interface {
	CreateProblem(ctx context.Context, req *CreateProblemRequest, opts ...http.CallOption) (rsp *CreateProblemResponse, err error)
	CreateProblemFile(ctx context.Context, req *CreateProblemFileRequest, opts ...http.CallOption) (rsp *ProblemFile, err error)
	CreateProblemStatement(ctx context.Context, req *CreateProblemStatementRequest, opts ...http.CallOption) (rsp *ProblemStatement, err error)
	CreateProblemTest(ctx context.Context, req *CreateProblemTestRequest, opts ...http.CallOption) (rsp *ProblemTest, err error)
	DeleteProblemFile(ctx context.Context, req *DeleteProblemFileRequest, opts ...http.CallOption) (rsp *ProblemFile, err error)
	DeleteProblemStatement(ctx context.Context, req *DeleteProblemStatementRequest, opts ...http.CallOption) (rsp *ProblemStatement, err error)
	DeleteProblemTest(ctx context.Context, req *DeleteProblemTestRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetProblem(ctx context.Context, req *GetProblemRequest, opts ...http.CallOption) (rsp *Problem, err error)
	GetProblemFile(ctx context.Context, req *GetProblemFileRequest, opts ...http.CallOption) (rsp *ProblemFile, err error)
	GetProblemStatement(ctx context.Context, req *GetProblemStatementRequest, opts ...http.CallOption) (rsp *ProblemStatement, err error)
	GetProblemTest(ctx context.Context, req *GetProblemTestRequest, opts ...http.CallOption) (rsp *ProblemTest, err error)
	GetProblemVerification(ctx context.Context, req *GetProblemVerificationRequest, opts ...http.CallOption) (rsp *ProblemVerification, err error)
	ListProblemFiles(ctx context.Context, req *ListProblemFilesRequest, opts ...http.CallOption) (rsp *ListProblemFilesResponse, err error)
	ListProblemStatements(ctx context.Context, req *ListProblemStatementsRequest, opts ...http.CallOption) (rsp *ListProblemStatementsResponse, err error)
	ListProblemStdCheckers(ctx context.Context, req *ListProblemStdCheckersRequest, opts ...http.CallOption) (rsp *ListProblemStdCheckersResponse, err error)
	ListProblemTests(ctx context.Context, req *ListProblemTestsRequest, opts ...http.CallOption) (rsp *ListProblemTestsResponse, err error)
	ListProblems(ctx context.Context, req *ListProblemsRequest, opts ...http.CallOption) (rsp *ListProblemsResponse, err error)
	RunProblemFile(ctx context.Context, req *RunProblemFileRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateProblem(ctx context.Context, req *UpdateProblemRequest, opts ...http.CallOption) (rsp *Problem, err error)
	UpdateProblemChecker(ctx context.Context, req *UpdateProblemCheckerRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateProblemFile(ctx context.Context, req *UpdateProblemFileRequest, opts ...http.CallOption) (rsp *ProblemFile, err error)
	UpdateProblemStatement(ctx context.Context, req *UpdateProblemStatementRequest, opts ...http.CallOption) (rsp *ProblemStatement, err error)
	UpdateProblemTest(ctx context.Context, req *UpdateProblemTestRequest, opts ...http.CallOption) (rsp *ProblemTest, err error)
	VerifyProblem(ctx context.Context, req *VerifyProblemRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type ProblemServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProblemServiceHTTPClient(client *http.Client) ProblemServiceHTTPClient {
	return &ProblemServiceHTTPClientImpl{client}
}

func (c *ProblemServiceHTTPClientImpl) CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...http.CallOption) (*CreateProblemResponse, error) {
	var out CreateProblemResponse
	pattern := "/problems"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceCreateProblem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) CreateProblemFile(ctx context.Context, in *CreateProblemFileRequest, opts ...http.CallOption) (*ProblemFile, error) {
	var out ProblemFile
	pattern := "/problems/{id}/files"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceCreateProblemFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) CreateProblemStatement(ctx context.Context, in *CreateProblemStatementRequest, opts ...http.CallOption) (*ProblemStatement, error) {
	var out ProblemStatement
	pattern := "/problems/{id}/statements"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceCreateProblemStatement))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) CreateProblemTest(ctx context.Context, in *CreateProblemTestRequest, opts ...http.CallOption) (*ProblemTest, error) {
	var out ProblemTest
	pattern := "/problems/{id}/tests"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceCreateProblemTest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) DeleteProblemFile(ctx context.Context, in *DeleteProblemFileRequest, opts ...http.CallOption) (*ProblemFile, error) {
	var out ProblemFile
	pattern := "/problems/{id}/files/{sid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceDeleteProblemFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) DeleteProblemStatement(ctx context.Context, in *DeleteProblemStatementRequest, opts ...http.CallOption) (*ProblemStatement, error) {
	var out ProblemStatement
	pattern := "/problems/{id}/statements/{sid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceDeleteProblemStatement))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) DeleteProblemTest(ctx context.Context, in *DeleteProblemTestRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/problems/{id}/tests/{tid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceDeleteProblemTest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) GetProblem(ctx context.Context, in *GetProblemRequest, opts ...http.CallOption) (*Problem, error) {
	var out Problem
	pattern := "/problems/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceGetProblem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) GetProblemFile(ctx context.Context, in *GetProblemFileRequest, opts ...http.CallOption) (*ProblemFile, error) {
	var out ProblemFile
	pattern := "/problems/{id}/files/{sid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceGetProblemFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) GetProblemStatement(ctx context.Context, in *GetProblemStatementRequest, opts ...http.CallOption) (*ProblemStatement, error) {
	var out ProblemStatement
	pattern := "/problems/{id}/statements"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceGetProblemStatement))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) GetProblemTest(ctx context.Context, in *GetProblemTestRequest, opts ...http.CallOption) (*ProblemTest, error) {
	var out ProblemTest
	pattern := "/problems/{id}/tests"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceGetProblemTest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) GetProblemVerification(ctx context.Context, in *GetProblemVerificationRequest, opts ...http.CallOption) (*ProblemVerification, error) {
	var out ProblemVerification
	pattern := "/problems/{id}/verification"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceGetProblemVerification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) ListProblemFiles(ctx context.Context, in *ListProblemFilesRequest, opts ...http.CallOption) (*ListProblemFilesResponse, error) {
	var out ListProblemFilesResponse
	pattern := "/problems/{id}/files"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceListProblemFiles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) ListProblemStatements(ctx context.Context, in *ListProblemStatementsRequest, opts ...http.CallOption) (*ListProblemStatementsResponse, error) {
	var out ListProblemStatementsResponse
	pattern := "/problems/{id}/statements"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceListProblemStatements))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) ListProblemStdCheckers(ctx context.Context, in *ListProblemStdCheckersRequest, opts ...http.CallOption) (*ListProblemStdCheckersResponse, error) {
	var out ListProblemStdCheckersResponse
	pattern := "/problems/{id}/std_checkers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceListProblemStdCheckers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) ListProblemTests(ctx context.Context, in *ListProblemTestsRequest, opts ...http.CallOption) (*ListProblemTestsResponse, error) {
	var out ListProblemTestsResponse
	pattern := "/problems/{id}/tests"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceListProblemTests))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...http.CallOption) (*ListProblemsResponse, error) {
	var out ListProblemsResponse
	pattern := "/problems"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemServiceListProblems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) RunProblemFile(ctx context.Context, in *RunProblemFileRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/problem_files/{sid}/run"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceRunProblemFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) UpdateProblem(ctx context.Context, in *UpdateProblemRequest, opts ...http.CallOption) (*Problem, error) {
	var out Problem
	pattern := "/problems/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceUpdateProblem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) UpdateProblemChecker(ctx context.Context, in *UpdateProblemCheckerRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/problems/{id}/checkers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceUpdateProblemChecker))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) UpdateProblemFile(ctx context.Context, in *UpdateProblemFileRequest, opts ...http.CallOption) (*ProblemFile, error) {
	var out ProblemFile
	pattern := "/problems/{id}/files/{sid}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceUpdateProblemFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) UpdateProblemStatement(ctx context.Context, in *UpdateProblemStatementRequest, opts ...http.CallOption) (*ProblemStatement, error) {
	var out ProblemStatement
	pattern := "/problems/{id}/statements/{sid}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceUpdateProblemStatement))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) UpdateProblemTest(ctx context.Context, in *UpdateProblemTestRequest, opts ...http.CallOption) (*ProblemTest, error) {
	var out ProblemTest
	pattern := "/problems/{id}/tests/{tid}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceUpdateProblemTest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProblemServiceHTTPClientImpl) VerifyProblem(ctx context.Context, in *VerifyProblemRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/problems/{id}/verify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemServiceVerifyProblem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
