// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: v1/ranking.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProblemRankingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListProblemRankingsRequest) Reset() {
	*x = ListProblemRankingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ranking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProblemRankingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemRankingsRequest) ProtoMessage() {}

func (x *ListProblemRankingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ranking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemRankingsRequest.ProtoReflect.Descriptor instead.
func (*ListProblemRankingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_ranking_proto_rawDescGZIP(), []int{0}
}

type ProblemRanking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank     int32  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId   int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Solved   int32  `protobuf:"varint,3,opt,name=solved,proto3" json:"solved,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *ProblemRanking) Reset() {
	*x = ProblemRanking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ranking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemRanking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemRanking) ProtoMessage() {}

func (x *ProblemRanking) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ranking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemRanking.ProtoReflect.Descriptor instead.
func (*ProblemRanking) Descriptor() ([]byte, []int) {
	return file_v1_ranking_proto_rawDescGZIP(), []int{1}
}

func (x *ProblemRanking) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ProblemRanking) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProblemRanking) GetSolved() int32 {
	if x != nil {
		return x.Solved
	}
	return 0
}

func (x *ProblemRanking) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type ListProblemRankingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*ProblemRanking `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total int64             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListProblemRankingsResponse) Reset() {
	*x = ListProblemRankingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ranking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProblemRankingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemRankingsResponse) ProtoMessage() {}

func (x *ListProblemRankingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ranking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemRankingsResponse.ProtoReflect.Descriptor instead.
func (*ListProblemRankingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_ranking_proto_rawDescGZIP(), []int{2}
}

func (x *ListProblemRankingsResponse) GetData() []*ProblemRanking {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListProblemRankingsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_v1_ranking_proto protoreflect.FileDescriptor

var file_v1_ranking_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x31, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x6a, 0x6e, 0x6f, 0x6a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x71, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x6a, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6a, 0x6e, 0x6f, 0x6a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x32, 0xa2, 0x01, 0x0a, 0x0e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x8f, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x2d, 0x2e, 0x6a, 0x6e,
	0x6f, 0x6a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6a, 0x6e, 0x6f,
	0x6a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x13, 0x12, 0x11, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x72, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x15, 0x5a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_ranking_proto_rawDescOnce sync.Once
	file_v1_ranking_proto_rawDescData = file_v1_ranking_proto_rawDesc
)

func file_v1_ranking_proto_rawDescGZIP() []byte {
	file_v1_ranking_proto_rawDescOnce.Do(func() {
		file_v1_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_ranking_proto_rawDescData)
	})
	return file_v1_ranking_proto_rawDescData
}

var file_v1_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_ranking_proto_goTypes = []interface{}{
	(*ListProblemRankingsRequest)(nil),  // 0: jnoj.interface.v1.ListProblemRankingsRequest
	(*ProblemRanking)(nil),              // 1: jnoj.interface.v1.ProblemRanking
	(*ListProblemRankingsResponse)(nil), // 2: jnoj.interface.v1.ListProblemRankingsResponse
}
var file_v1_ranking_proto_depIdxs = []int32{
	1, // 0: jnoj.interface.v1.ListProblemRankingsResponse.data:type_name -> jnoj.interface.v1.ProblemRanking
	0, // 1: jnoj.interface.v1.RankingService.ListProblemRankings:input_type -> jnoj.interface.v1.ListProblemRankingsRequest
	2, // 2: jnoj.interface.v1.RankingService.ListProblemRankings:output_type -> jnoj.interface.v1.ListProblemRankingsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_ranking_proto_init() }
func file_v1_ranking_proto_init() {
	if File_v1_ranking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_ranking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProblemRankingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ranking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemRanking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ranking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProblemRankingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_ranking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_ranking_proto_goTypes,
		DependencyIndexes: file_v1_ranking_proto_depIdxs,
		MessageInfos:      file_v1_ranking_proto_msgTypes,
	}.Build()
	File_v1_ranking_proto = out.File
	file_v1_ranking_proto_rawDesc = nil
	file_v1_ranking_proto_goTypes = nil
	file_v1_ranking_proto_depIdxs = nil
}
