// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.4
// - protoc             v3.21.12
// source: v1/admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	auth "jnoj/internal/middleware/auth"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

// auth.
const OperationAdminServiceListServiceStatuses = "/jnoj.admin.v1.AdminService/ListServiceStatuses"

type AdminServiceHTTPServer interface {
	ListServiceStatuses(context.Context, *ListServiceStatusesRequest) (*ListServiceStatusesResponse, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	s.Use("/jnoj.admin.v1.AdminService/ListServiceStatuses", auth.User())
	r := s.Route("/")
	r.GET("/service_statuses", _AdminService_ListServiceStatuses0_HTTP_Handler(srv))
}

func _AdminService_ListServiceStatuses0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListServiceStatusesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListServiceStatuses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListServiceStatuses(ctx, req.(*ListServiceStatusesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListServiceStatusesResponse)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	ListServiceStatuses(ctx context.Context, req *ListServiceStatusesRequest, opts ...http.CallOption) (rsp *ListServiceStatusesResponse, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

func (c *AdminServiceHTTPClientImpl) ListServiceStatuses(ctx context.Context, in *ListServiceStatusesRequest, opts ...http.CallOption) (*ListServiceStatusesResponse, error) {
	var out ListServiceStatusesResponse
	pattern := "/service_statuses"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListServiceStatuses))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
