// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: v1/submission.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmissionEntityType int32

const (
	SubmissionEntityType_PROBLEMSET   SubmissionEntityType = 0
	SubmissionEntityType_CONTEST      SubmissionEntityType = 1
	SubmissionEntityType_PROBLEM_FILE SubmissionEntityType = 2
)

// Enum value maps for SubmissionEntityType.
var (
	SubmissionEntityType_name = map[int32]string{
		0: "PROBLEMSET",
		1: "CONTEST",
		2: "PROBLEM_FILE",
	}
	SubmissionEntityType_value = map[string]int32{
		"PROBLEMSET":   0,
		"CONTEST":      1,
		"PROBLEM_FILE": 2,
	}
)

func (x SubmissionEntityType) Enum() *SubmissionEntityType {
	p := new(SubmissionEntityType)
	*p = x
	return p
}

func (x SubmissionEntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmissionEntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_submission_proto_enumTypes[0].Descriptor()
}

func (SubmissionEntityType) Type() protoreflect.EnumType {
	return &file_v1_submission_proto_enumTypes[0]
}

func (x SubmissionEntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmissionEntityType.Descriptor instead.
func (SubmissionEntityType) EnumDescriptor() ([]byte, []int) {
	return file_v1_submission_proto_rawDescGZIP(), []int{0}
}

type RejudgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//
	//	*RejudgeRequest_ContestId
	//	*RejudgeRequest_ProblemId
	//	*RejudgeRequest_SubmissionId
	Id isRejudgeRequest_Id `protobuf_oneof:"id"`
}

func (x *RejudgeRequest) Reset() {
	*x = RejudgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_submission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejudgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejudgeRequest) ProtoMessage() {}

func (x *RejudgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_submission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejudgeRequest.ProtoReflect.Descriptor instead.
func (*RejudgeRequest) Descriptor() ([]byte, []int) {
	return file_v1_submission_proto_rawDescGZIP(), []int{0}
}

func (m *RejudgeRequest) GetId() isRejudgeRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *RejudgeRequest) GetContestId() int32 {
	if x, ok := x.GetId().(*RejudgeRequest_ContestId); ok {
		return x.ContestId
	}
	return 0
}

func (x *RejudgeRequest) GetProblemId() int32 {
	if x, ok := x.GetId().(*RejudgeRequest_ProblemId); ok {
		return x.ProblemId
	}
	return 0
}

func (x *RejudgeRequest) GetSubmissionId() int32 {
	if x, ok := x.GetId().(*RejudgeRequest_SubmissionId); ok {
		return x.SubmissionId
	}
	return 0
}

type isRejudgeRequest_Id interface {
	isRejudgeRequest_Id()
}

type RejudgeRequest_ContestId struct {
	ContestId int32 `protobuf:"varint,1,opt,name=contest_id,json=contestId,proto3,oneof"`
}

type RejudgeRequest_ProblemId struct {
	ProblemId int32 `protobuf:"varint,2,opt,name=problem_id,json=problemId,proto3,oneof"`
}

type RejudgeRequest_SubmissionId struct {
	SubmissionId int32 `protobuf:"varint,3,opt,name=submission_id,json=submissionId,proto3,oneof"`
}

func (*RejudgeRequest_ContestId) isRejudgeRequest_Id() {}

func (*RejudgeRequest_ProblemId) isRejudgeRequest_Id() {}

func (*RejudgeRequest_SubmissionId) isRejudgeRequest_Id() {}

type ListSubmissionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       int32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage    int32                 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	EntityType *SubmissionEntityType `protobuf:"varint,3,opt,name=entity_type,json=entityType,proto3,enum=jnoj.interface.v1.SubmissionEntityType,oneof" json:"entity_type,omitempty"`
	EntityId   int32                 `protobuf:"varint,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ProblemId  int32                 `protobuf:"varint,5,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Ids        []int32               `protobuf:"varint,6,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ListSubmissionsRequest) Reset() {
	*x = ListSubmissionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_submission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSubmissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsRequest) ProtoMessage() {}

func (x *ListSubmissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_submission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubmissionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_submission_proto_rawDescGZIP(), []int{1}
}

func (x *ListSubmissionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSubmissionsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListSubmissionsRequest) GetEntityType() SubmissionEntityType {
	if x != nil && x.EntityType != nil {
		return *x.EntityType
	}
	return SubmissionEntityType_PROBLEMSET
}

func (x *ListSubmissionsRequest) GetEntityId() int32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ListSubmissionsRequest) GetProblemId() int32 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *ListSubmissionsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_v1_submission_proto protoreflect.FileDescriptor

var file_v1_submission_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6a, 0x6e, 0x6f, 0x6a, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a,
	0x0e, 0x52, 0x65, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x02, 0x69, 0x64, 0x12, 0x03,
	0xf8, 0x42, 0x01, 0x22, 0xf4, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x4d, 0x0a,
	0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6a, 0x6e, 0x6f, 0x6a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x45, 0x0a, 0x14, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x42, 0x4c, 0x45, 0x4d, 0x53, 0x45, 0x54,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x52, 0x4f, 0x42, 0x4c, 0x45, 0x4d, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10,
	0x02, 0x32, 0x6e, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x07, 0x52, 0x65, 0x6a, 0x75, 0x64, 0x67,
	0x65, 0x12, 0x21, 0x2e, 0x6a, 0x6e, 0x6f, 0x6a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x13, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0d, 0x22, 0x08, 0x2f, 0x72, 0x65, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x3a, 0x01,
	0x2a, 0x42, 0x15, 0x5a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_submission_proto_rawDescOnce sync.Once
	file_v1_submission_proto_rawDescData = file_v1_submission_proto_rawDesc
)

func file_v1_submission_proto_rawDescGZIP() []byte {
	file_v1_submission_proto_rawDescOnce.Do(func() {
		file_v1_submission_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_submission_proto_rawDescData)
	})
	return file_v1_submission_proto_rawDescData
}

var file_v1_submission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_submission_proto_goTypes = []interface{}{
	(SubmissionEntityType)(0),      // 0: jnoj.interface.v1.SubmissionEntityType
	(*RejudgeRequest)(nil),         // 1: jnoj.interface.v1.RejudgeRequest
	(*ListSubmissionsRequest)(nil), // 2: jnoj.interface.v1.ListSubmissionsRequest
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_v1_submission_proto_depIdxs = []int32{
	0, // 0: jnoj.interface.v1.ListSubmissionsRequest.entity_type:type_name -> jnoj.interface.v1.SubmissionEntityType
	1, // 1: jnoj.interface.v1.SubmissionService.Rejudge:input_type -> jnoj.interface.v1.RejudgeRequest
	3, // 2: jnoj.interface.v1.SubmissionService.Rejudge:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_submission_proto_init() }
func file_v1_submission_proto_init() {
	if File_v1_submission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_submission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejudgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_submission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSubmissionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_submission_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RejudgeRequest_ContestId)(nil),
		(*RejudgeRequest_ProblemId)(nil),
		(*RejudgeRequest_SubmissionId)(nil),
	}
	file_v1_submission_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_submission_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_submission_proto_goTypes,
		DependencyIndexes: file_v1_submission_proto_depIdxs,
		EnumInfos:         file_v1_submission_proto_enumTypes,
		MessageInfos:      file_v1_submission_proto_msgTypes,
	}.Build()
	File_v1_submission_proto = out.File
	file_v1_submission_proto_rawDesc = nil
	file_v1_submission_proto_goTypes = nil
	file_v1_submission_proto_depIdxs = nil
}
