// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"jnoj/app/interface/internal/biz"
	"jnoj/app/interface/internal/conf"
	"jnoj/app/interface/internal/data"
	"jnoj/app/interface/internal/server"
	"jnoj/app/interface/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confService *conf.Service, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	contestRepo := data.NewContestRepo(dataData, logger)
	problemRepo := data.NewProblemRepo(dataData, logger)
	submissionRepo := data.NewSubmissionRepo(dataData, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	groupRepo := data.NewGroupRepo(dataData, logger)
	contestUsecase := biz.NewContestUsecase(contestRepo, problemRepo, submissionRepo, userRepo, groupRepo, logger)
	discovery := biz.NewDiscovery(registry)
	sandboxServiceClient := biz.NewSandboxClient(discovery)
	problemUsecase := biz.NewProblemUsecase(problemRepo, sandboxServiceClient, logger, submissionRepo)
	contestService := service.NewContestService(contestUsecase, problemUsecase)
	userUsecase := biz.NewUserUsecase(userRepo, confService, logger)
	userService := service.NewUserService(userUsecase)
	problemsetRepo := data.NewProblemsetRepo(dataData, logger)
	problemsetUsecase := biz.NewProblemsetUsecase(problemsetRepo, problemRepo, submissionRepo, logger)
	problemService := service.NewProblemService(problemUsecase, problemsetUsecase, logger)
	submissionUsecase := biz.NewSubmissionUsecase(submissionRepo, problemRepo, contestRepo, problemsetRepo, sandboxServiceClient, logger)
	submissionService := service.NewSubmissionService(submissionUsecase)
	sandboxRepo := data.NewSandboxRepo(dataData, logger)
	sandboxUsecase := biz.NewSandboxUsecase(sandboxServiceClient, problemRepo, sandboxRepo, logger)
	sandboxService := service.NewSandboxService(sandboxUsecase)
	groupUsecase := biz.NewGroupUsecase(groupRepo, userRepo, logger)
	groupService := service.NewGroupService(groupUsecase)
	webSocketRepo := data.NewWebSocketRepo(dataData)
	webSocketUsecase := biz.NewWebSocketUsecase(confService, webSocketRepo, logger)
	webSocketService := service.NewWebSocketService(webSocketUsecase, logger)
	rankingRepo := data.NewRankingRepo(dataData, logger)
	rankingUsecase := biz.NewRankingUsecase(rankingRepo, logger)
	rankingService := service.NewRankingService(rankingUsecase)
	postRepo := data.NewPostRepo(dataData, logger)
	postUsecase := biz.NewPostUsecase(postRepo, userRepo, contestRepo, logger)
	postService := service.NewPostService(postUsecase)
	httpServer := server.NewHTTPServer(confServer, contestService, userService, problemService, submissionService, sandboxService, groupService, webSocketService, rankingService, postService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
