// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"jnoj/app/interface/internal/biz"
	"jnoj/app/interface/internal/conf"
	"jnoj/app/interface/internal/data"
	"jnoj/app/interface/internal/server"
	"jnoj/app/interface/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	contestRepo := data.NewContestRepo(dataData, logger)
	contestUsecase := biz.NewContestUsecase(contestRepo, logger)
	contestService := service.NewContestService(contestUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase)
	problemRepo := data.NewProblemRepo(dataData, logger)
	problemUsecase := biz.NewProblemUsecase(problemRepo, logger)
	problemService := service.NewProblemService(problemUsecase)
	httpServer := server.NewHTTPServer(confServer, contestService, userService, problemService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
