server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
data:
  database:
    driver: mysql
    source: "${MYSQL_SOURCE}"
  redis:
    addr: "${REDIS_ADDR}"
    read_timeout: 0.2s
    write_timeout: 0.2s
  object_storage:
    private_bucket:
      bucket: "private"
      secret_id: "{S3_SECRET_ID}"
      secret_key: "{S3_SECRET_KEY}"
      endpoint: "${JNOJ_HOST}/s3"
    public_bucket:
      bucket: "public"
      secret_id: "{S3_SECRET_ID}"
      secret_key: "{S3_SECRET_KEY}"
      endpoint: "${JNOJ_HOST}/s3"
  message_queue:
    address: "amqp://admin:admin@rabbitmq:5672/"
service:
  smtp:
    ssl: true
    address: smtp.exmail.qq.com:465
    username: no-reply@jnoj.dev
    password: GKce4Jj7F8tBzkYQ
    host: smtp.exmail.qq.com

consul:
  address: consul:8500
  scheme: http