<?php
$category_map["Graph Theory"] = "Graph Theory";
$category_map["Graph Theory"] = "Graph Theory";
$category_map["graphs"] = "Graph Theory";
$category_map["2-SAT"] = "2-SAT";
$category_map["2-sat"] = "2-SAT";
$category_map["Articulation/Bridge/Biconnected Component"] = "Articulation/Bridge/Biconnected Component";
$category_map["Cycles/Topological Sorting/Strongly Connected Component"] = "Cycles/Topological Sorting/Strongly Connected Component";
$category_map["shortest paths"] = "Shortest Path";
$category_map["Bellman Ford"] = "Bellman Ford";
$category_map["Dijkstra/Floyd Warshall"] = "Dijkstra/Floyd Warshall";
$category_map["Euler Trail/Circuit"] = "Euler Trail/Circuit";
$category_map["Heavy-Light Decomposition"] = "Heavy-Light Decomposition";
$category_map["Minimum Spanning Tree"] = "Minimum Spanning Tree";
$category_map["Stable Marriage Problem"] = "Stable Marriage Problem";
$category_map["trees"] = "Trees";
$category_map["Directed Minimum Spanning Tree"] = "Directed Minimum Spanning Tree";
$category_map["Flow/Matching"] = "Flow/Matching";
$category_map["graph matchings"] = "Graph Matching";
$category_map["Bipartite Matching"] = "Bipartite Matching";
$category_map["Hopcroft–Karp Bipartite Matching"] = "Hopcroft–Karp Bipartite Matching";
$category_map["Weighted Bipartite Matching/Hungarian Algorithm"] = "Weighted Bipartite Matching/Hungarian Algorithm";
$category_map["flows"] = "Flow";
$category_map["Max Flow/Min Cut"] = "Max Flow/Min Cut";
$category_map["Min Cost Max Flow"] = "Min Cost Max Flow";
$category_map["Recursion/Branch and Bound"] = "DFS-like";
$category_map["dfs and similar"] = "DFS-like";
$category_map["Backtracking with Pruning/Branch and Bound"] = "Backtracking with Pruning/Branch and Bound";
$category_map["Basic Recursion"] = "Basic Recursion";
$category_map["IDA* Search"] = "IDA* Search";
$category_map["Parsing/Grammar"] = "Parsing/Grammar";
$category_map["expression parsing"] = "Parsing/Grammar";
$category_map["Breadth First Search/Depth First Search"] = "Breadth First Search/Depth First Search";
$category_map["Advanced Search Techniques"] = "Advanced Search Techniques";
$category_map["Binary Search/Bisection"] = "Binary Search/Bisection";
$category_map["binary search"] = "Binary Search/Bisection";
$category_map["Ternary Search"] = "Ternary Search";
$category_map["ternary search"] = "Ternary Search";
$category_map["Geometry"] = "Geometry";
$category_map["Geometry"] = "Geometry";
$category_map["geometry"] = "Geometry";
$category_map["Basic Geometry"] = "Basic Geometry";
$category_map["Computational Geometry"] = "Computational Geometry";
$category_map["Convex Hull"] = "Convex Hull";
$category_map["Pick`s theorem"] = "Pick's Theorem";
$category_map["Game Theory"] = "Game Theory";
$category_map["Game"] = "Game Theory";
$category_map["games"] = "Game Theory";
$category_map["Green Hackenbush/Colon Principle/Fusion Principle"] = "Green Hackenbush/Colon Principle/Fusion Principle";
$category_map["Nim"] = "Nim";
$category_map["Sprague-Grundy Number"] = "Sprague-Grundy Number";
$category_map["Matrix"] = "Matrix";
$category_map["matrices"] = "Matrix";
$category_map["Gaussian Elimination"] = "Gaussian Elimination";
$category_map["Matrix Exponentiation"] = "Matrix Exponentiation";
$category_map["Data Structures"] = "Data Structures";
$category_map["Data Structures"] = "Data Structures";
$category_map["data structures"] = "Data Structures";
$category_map["Basic Data Structures"] = "Basic Data Structures";
$category_map["Binary Indexed Tree"] = "Binary Indexed Tree";
$category_map["Binary Search Tree"] = "Binary Search Tree";
$category_map["Hashing"] = "Hashing";
$category_map["hashing"] = "Hashing";
$category_map["Orthogonal Range Search"] = "Orthogonal Range Search";
$category_map["Range Minimum Query/Lowest Common Ancestor"] = "Range Minimum Query/Lowest Common Ancestor";
$category_map["Segment Tree/Interval Tree"] = "Segment Tree/Interval Tree";
$category_map["Trie Tree"] = "Trie Tree";
$category_map["sortings"] = "Sorting";
$category_map["dsu"] = "Disjoint Set";
$category_map["String"] = "String";
$category_map["String Algorithms"] = "String";
$category_map["strings"] = "String";
$category_map["Aho Corasick"] = "Aho Corasick";
$category_map["Knuth-Morris-Pratt"] = "Knuth-Morris-Pratt";
$category_map["Suffix Array/Suffix Tree"] = "Suffix Array/Suffix Tree";
$category_map["string suffix structures"] = "Suffix Array/Suffix Tree";
$category_map["Math"] = "Math";
$category_map["math"] = "Math";
$category_map["Basic Math"] = "Basic Math";
$category_map["Big Integer Arithmetic"] = "Big Integer Arithmetic";
$category_map["Number Theory"] = "Number Theory";
$category_map["Number Theory"] = "Number Theory";
$category_map["number theory"] = "Number Theory";
$category_map["Chinese Remainder Theorem"] = "Chinese Remainder Theorem";
$category_map["Extended Euclid"] = "Extended Euclid";
$category_map["Inclusion/Exclusion"] = "Inclusion/Exclusion";
$category_map["Modular Arithmetic"] = "Modular Arithmetic";
$category_map["combinatorics"] = "Combinatorics";
$category_map["Group Theory/Burnside`s lemma"] = "Group Theory/Burnside's lemma";
$category_map["Counting"] = "Counting";
$category_map["Probability/Expected Value"] = "Probability/Expected Value";
$category_map["probabilities"] = "Probability/Expected Value";
$category_map["Others"] = "Others";
$category_map["Tricky"] = "Tricky";
$category_map["Hardest"] = "Hardest";
$category_map["Unusual"] = "Unusual";
$category_map["brute force"] = "Brute Force";
$category_map["implementation"] = "Implementation";
$category_map["constructive algorithms"] = "Constructive Algorithms";
$category_map["two pointers"] = "Two Pointer";
$category_map["bitmasks"] = "Bitmask";
$category_map["Beginners Problems"] = "Beginner";
$category_map["Beginners"] = "Beginner";
$category_map["Discrete Logarithm/Shank`s Baby-step Giant-step Algorithm"] = "Discrete Logarithm/Shank's Baby-step Giant-step Algorithm";
$category_map["Dynamic Programming"] = "Dynamic Programming";
$category_map["Dynamic Programming"] = "Dynamic Programming";
$category_map["dp"] = "Dynamic Programming";
$category_map["Greedy"] = "Greedy";
$category_map["greedy"] = "Greedy";
$category_map["Divide and Conquer"] = "Divide and Conquer";
$category_map["divide and conquer"] = "Divide and Conquer";

$category_key["Graph Theory"] = 1;
$category_key["2-SAT"] = 2;
$category_key["Articulation/Bridge/Biconnected Component"] = 3;
$category_key["Cycles/Topological Sorting/Strongly Connected Component"] = 4;
$category_key["Shortest Path"] = 5;
$category_key["Bellman Ford"] = 6;
$category_key["Dijkstra/Floyd Warshall"] = 7;
$category_key["Euler Trail/Circuit"] = 8;
$category_key["Heavy-Light Decomposition"] = 9;
$category_key["Minimum Spanning Tree"] = 10;
$category_key["Stable Marriage Problem"] = 11;
$category_key["Trees"] = 12;
$category_key["Directed Minimum Spanning Tree"] = 13;
$category_key["Flow/Matching"] = 14;
$category_key["Graph Matching"] = 15;
$category_key["Bipartite Matching"] = 16;
$category_key["Hopcroft–Karp Bipartite Matching"] = 17;
$category_key["Weighted Bipartite Matching/Hungarian Algorithm"] = 18;
$category_key["Flow"] = 19;
$category_key["Max Flow/Min Cut"] = 20;
$category_key["Min Cost Max Flow"] = 21;
$category_key["DFS-like"] = 22;
$category_key["Backtracking with Pruning/Branch and Bound"] = 23;
$category_key["Basic Recursion"] = 24;
$category_key["IDA* Search"] = 25;
$category_key["Parsing/Grammar"] = 26;
$category_key["Breadth First Search/Depth First Search"] = 27;
$category_key["Advanced Search Techniques"] = 28;
$category_key["Binary Search/Bisection"] = 29;
$category_key["Ternary Search"] = 30;
$category_key["Geometry"] = 31;
$category_key["Basic Geometry"] = 32;
$category_key["Computational Geometry"] = 33;
$category_key["Convex Hull"] = 34;
$category_key["Pick's Theorem"] = 35;
$category_key["Game Theory"] = 36;
$category_key["Green Hackenbush/Colon Principle/Fusion Principle"] = 37;
$category_key["Nim"] = 38;
$category_key["Sprague-Grundy Number"] = 39;
$category_key["Matrix"] = 40;
$category_key["Gaussian Elimination"] = 41;
$category_key["Matrix Exponentiation"] = 42;
$category_key["Data Structures"] = 43;
$category_key["Basic Data Structures"] = 44;
$category_key["Binary Indexed Tree"] = 45;
$category_key["Binary Search Tree"] = 46;
$category_key["Hashing"] = 47;
$category_key["Orthogonal Range Search"] = 48;
$category_key["Range Minimum Query/Lowest Common Ancestor"] = 49;
$category_key["Segment Tree/Interval Tree"] = 50;
$category_key["Trie Tree"] = 51;
$category_key["Sorting"] = 52;
$category_key["Disjoint Set"] = 53;
$category_key["String"] = 54;
$category_key["Aho Corasick"] = 55;
$category_key["Knuth-Morris-Pratt"] = 56;
$category_key["Suffix Array/Suffix Tree"] = 57;
$category_key["Math"] = 58;
$category_key["Basic Math"] = 59;
$category_key["Big Integer Arithmetic"] = 60;
$category_key["Number Theory"] = 61;
$category_key["Chinese Remainder Theorem"] = 62;
$category_key["Extended Euclid"] = 63;
$category_key["Inclusion/Exclusion"] = 64;
$category_key["Modular Arithmetic"] = 65;
$category_key["Combinatorics"] = 66;
$category_key["Group Theory/Burnside's lemma"] = 67;
$category_key["Counting"] = 68;
$category_key["Probability/Expected Value"] = 69;
$category_key["Others"] = 70;
$category_key["Tricky"] = 71;
$category_key["Hardest"] = 72;
$category_key["Unusual"] = 73;
$category_key["Brute Force"] = 74;
$category_key["Implementation"] = 75;
$category_key["Constructive Algorithms"] = 76;
$category_key["Two Pointer"] = 77;
$category_key["Bitmask"] = 78;
$category_key["Beginner"] = 79;
$category_key["Discrete Logarithm/Shank's Baby-step Giant-step Algorithm"] = 80;
$category_key["Dynamic Programming"] = 81;
$category_key["Greedy"] = 82;
$category_key["Divide and Conquer"] = 83;


$category_name["1"] = "Graph Theory";
$category_name["2"] = "2-SAT";
$category_name["3"] = "Articulation/Bridge/Biconnected Component";
$category_name["4"] = "Cycles/Topological Sorting/Strongly Connected Component";
$category_name["5"] = "Shortest Path";
$category_name["6"] = "Bellman Ford";
$category_name["7"] = "Dijkstra/Floyd Warshall";
$category_name["8"] = "Euler Trail/Circuit";
$category_name["9"] = "Heavy-Light Decomposition";
$category_name["10"] = "Minimum Spanning Tree";
$category_name["11"] = "Stable Marriage Problem";
$category_name["12"] = "Trees";
$category_name["13"] = "Directed Minimum Spanning Tree";
$category_name["14"] = "Flow/Matching";
$category_name["15"] = "Graph Matching";
$category_name["16"] = "Bipartite Matching";
$category_name["17"] = "Hopcroft–Karp Bipartite Matching";
$category_name["18"] = "Weighted Bipartite Matching/Hungarian Algorithm";
$category_name["19"] = "Flow";
$category_name["20"] = "Max Flow/Min Cut";
$category_name["21"] = "Min Cost Max Flow";
$category_name["22"] = "DFS-like";
$category_name["23"] = "Backtracking with Pruning/Branch and Bound";
$category_name["24"] = "Basic Recursion";
$category_name["25"] = "IDA* Search";
$category_name["26"] = "Parsing/Grammar";
$category_name["27"] = "Breadth First Search/Depth First Search";
$category_name["28"] = "Advanced Search Techniques";
$category_name["29"] = "Binary Search/Bisection";
$category_name["30"] = "Ternary Search";
$category_name["31"] = "Geometry";
$category_name["32"] = "Basic Geometry";
$category_name["33"] = "Computational Geometry";
$category_name["34"] = "Convex Hull";
$category_name["35"] = "Pick's Theorem";
$category_name["36"] = "Game Theory";
$category_name["37"] = "Green Hackenbush/Colon Principle/Fusion Principle";
$category_name["38"] = "Nim";
$category_name["39"] = "Sprague-Grundy Number";
$category_name["40"] = "Matrix";
$category_name["41"] = "Gaussian Elimination";
$category_name["42"] = "Matrix Exponentiation";
$category_name["43"] = "Data Structures";
$category_name["44"] = "Basic Data Structures";
$category_name["45"] = "Binary Indexed Tree";
$category_name["46"] = "Binary Search Tree";
$category_name["47"] = "Hashing";
$category_name["48"] = "Orthogonal Range Search";
$category_name["49"] = "Range Minimum Query/Lowest Common Ancestor";
$category_name["50"] = "Segment Tree/Interval Tree";
$category_name["51"] = "Trie Tree";
$category_name["52"] = "Sorting";
$category_name["53"] = "Disjoint Set";
$category_name["54"] = "String";
$category_name["55"] = "Aho Corasick";
$category_name["56"] = "Knuth-Morris-Pratt";
$category_name["57"] = "Suffix Array/Suffix Tree";
$category_name["58"] = "Math";
$category_name["59"] = "Basic Math";
$category_name["60"] = "Big Integer Arithmetic";
$category_name["61"] = "Number Theory";
$category_name["62"] = "Chinese Remainder Theorem";
$category_name["63"] = "Extended Euclid";
$category_name["64"] = "Inclusion/Exclusion";
$category_name["65"] = "Modular Arithmetic";
$category_name["66"] = "Combinatorics";
$category_name["67"] = "Group Theory/Burnside's lemma";
$category_name["68"] = "Counting";
$category_name["69"] = "Probability/Expected Value";
$category_name["70"] = "Others";
$category_name["71"] = "Tricky";
$category_name["72"] = "Hardest";
$category_name["73"] = "Unusual";
$category_name["74"] = "Brute Force";
$category_name["75"] = "Implementation";
$category_name["76"] = "Constructive Algorithms";
$category_name["77"] = "Two Pointer";
$category_name["78"] = "Bitmask";
$category_name["79"] = "Beginner";
$category_name["80"] = "Discrete Logarithm/Shank's Baby-step Giant-step Algorithm";
$category_name["81"] = "Dynamic Programming";
$category_name["82"] = "Greedy";
$category_name["83"] = "Divide and Conquer";


$category_father["Graph Theory"] = $category_father[1] = -1;
$category_father["2-SAT"] = $category_father[2] = 1;
$category_father["Articulation/Bridge/Biconnected Component"] = $category_father[3] = 1;
$category_father["Cycles/Topological Sorting/Strongly Connected Component"] = $category_father[4] = 1;
$category_father["Shortest Path"] = $category_father[5] = 1;
$category_father["Bellman Ford"] = $category_father[6] = 5;
$category_father["Dijkstra/Floyd Warshall"] = $category_father[7] = 5;
$category_father["Euler Trail/Circuit"] = $category_father[8] = 1;
$category_father["Heavy-Light Decomposition"] = $category_father[9] = 1;
$category_father["Minimum Spanning Tree"] = $category_father[10] = 1;
$category_father["Stable Marriage Problem"] = $category_father[11] = 1;
$category_father["Trees"] = $category_father[12] = 1;
$category_father["Directed Minimum Spanning Tree"] = $category_father[13] = 1;
$category_father["Flow/Matching"] = $category_father[14] = 1;
$category_father["Graph Matching"] = $category_father[15] = 14;
$category_father["Bipartite Matching"] = $category_father[16] = 15;
$category_father["Hopcroft–Karp Bipartite Matching"] = $category_father[17] = 15;
$category_father["Weighted Bipartite Matching/Hungarian Algorithm"] = $category_father[18] = 15;
$category_father["Flow"] = $category_father[19] = 14;
$category_father["Max Flow/Min Cut"] = $category_father[20] = 19;
$category_father["Min Cost Max Flow"] = $category_father[21] = 19;
$category_father["DFS-like"] = $category_father[22] = -1;
$category_father["Backtracking with Pruning/Branch and Bound"] = $category_father[23] = 22;
$category_father["Basic Recursion"] = $category_father[24] = 22;
$category_father["IDA* Search"] = $category_father[25] = 22;
$category_father["Parsing/Grammar"] = $category_father[26] = 22;
$category_father["Breadth First Search/Depth First Search"] = $category_father[27] = 22;
$category_father["Advanced Search Techniques"] = $category_father[28] = 22;
$category_father["Binary Search/Bisection"] = $category_father[29] = 28;
$category_father["Ternary Search"] = $category_father[30] = 28;
$category_father["Geometry"] = $category_father[31] = -1;
$category_father["Basic Geometry"] = $category_father[32] = 31;
$category_father["Computational Geometry"] = $category_father[33] = 31;
$category_father["Convex Hull"] = $category_father[34] = 31;
$category_father["Pick's Theorem"] = $category_father[35] = 31;
$category_father["Game Theory"] = $category_father[36] = -1;
$category_father["Green Hackenbush/Colon Principle/Fusion Principle"] = $category_father[37] = 36;
$category_father["Nim"] = $category_father[38] = 36;
$category_father["Sprague-Grundy Number"] = $category_father[39] = 36;
$category_father["Matrix"] = $category_father[40] = -1;
$category_father["Gaussian Elimination"] = $category_father[41] = 40;
$category_father["Matrix Exponentiation"] = $category_father[42] = 40;
$category_father["Data Structures"] = $category_father[43] = -1;
$category_father["Basic Data Structures"] = $category_father[44] = 43;
$category_father["Binary Indexed Tree"] = $category_father[45] = 43;
$category_father["Binary Search Tree"] = $category_father[46] = 43;
$category_father["Hashing"] = $category_father[47] = 43;
$category_father["Orthogonal Range Search"] = $category_father[48] = 43;
$category_father["Range Minimum Query/Lowest Common Ancestor"] = $category_father[49] = 43;
$category_father["Segment Tree/Interval Tree"] = $category_father[50] = 43;
$category_father["Trie Tree"] = $category_father[51] = 43;
$category_father["Sorting"] = $category_father[52] = 43;
$category_father["Disjoint Set"] = $category_father[53] = 43;
$category_father["String"] = $category_father[54] = -1;
$category_father["Aho Corasick"] = $category_father[55] = 54;
$category_father["Knuth-Morris-Pratt"] = $category_father[56] = 54;
$category_father["Suffix Array/Suffix Tree"] = $category_father[57] = 54;
$category_father["Math"] = $category_father[58] = -1;
$category_father["Basic Math"] = $category_father[59] = 58;
$category_father["Big Integer Arithmetic"] = $category_father[60] = 58;
$category_father["Number Theory"] = $category_father[61] = 58;
$category_father["Chinese Remainder Theorem"] = $category_father[62] = 61;
$category_father["Extended Euclid"] = $category_father[63] = 61;
$category_father["Inclusion/Exclusion"] = $category_father[64] = 61;
$category_father["Modular Arithmetic"] = $category_father[65] = 61;
$category_father["Combinatorics"] = $category_father[66] = 58;
$category_father["Group Theory/Burnside's lemma"] = $category_father[67] = 66;
$category_father["Counting"] = $category_father[68] = 66;
$category_father["Probability/Expected Value"] = $category_father[69] = 58;
$category_father["Others"] = $category_father[70] = -1;
$category_father["Tricky"] = $category_father[71] = 70;
$category_father["Hardest"] = $category_father[72] = 70;
$category_father["Unusual"] = $category_father[73] = 70;
$category_father["Brute Force"] = $category_father[74] = 70;
$category_father["Implementation"] = $category_father[75] = 70;
$category_father["Constructive Algorithms"] = $category_father[76] = 70;
$category_father["Two Pointer"] = $category_father[77] = 70;
$category_father["Bitmask"] = $category_father[78] = 70;
$category_father["Beginner"] = $category_father[79] = 70;
$category_father["Discrete Logarithm/Shank's Baby-step Giant-step Algorithm"] = $category_father[80] = 70;
$category_father["Dynamic Programming"] = $category_father[81] = -1;
$category_father["Greedy"] = $category_father[82] = 70;
$category_father["Divide and Conquer"] = $category_father[83] = 70;
